# Generated by Django 6.1 on 2026-09-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('BRL', 'Real (R$)'), ('USD', 'Dólar (US$)'), ('EUR', 'Euro (€)'), ('ARS', 'Peso Argentino ($)')], default='BRL', max_length=3, verbose_name='Moeda'),
        ),
    ]
