# Generated by Django 6.1 on 2026-08-31 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='Slug')),
                ('color_hex', models.CharField(default='#6B7280', help_text='Cor hexadecimal para gráficos e badges.', max_length=7, verbose_name='Cor (HEX)')),
                ('icon', models.CharField(default='bi-tag', help_text='Classe do Bootstrap Icons (ex: bi-cart-check).', max_length=50, verbose_name='Ícone')),
                ('type_scope', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa'), ('BOTH', 'Ambos')], default='EXPENSE', help_text='Define se a categoria aparece em receitas, despesas ou ambos.', max_length=10, verbose_name='Tipo')),
                ('is_default', models.BooleanField(default=False, help_text='Categorias padrão são criadas automaticamente para novos usuários.', verbose_name='Categoria padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor da movimentação em reais.', max_digits=12, verbose_name='Valor')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('description', models.CharField(help_text='Breve descrição da movimentação.', max_length=255, verbose_name='Descrição')),
                ('date', models.DateField(db_index=True, verbose_name='Data')),
                ('status', models.CharField(choices=[('COMPLETED', 'Concluída'), ('PENDING', 'Pendente')], default='COMPLETED', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', help_text='Notas opcionais sobre a movimentação.', verbose_name='Observações')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_category_per_user'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='idx_transaction_user_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type'], name='idx_transaction_user_type'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='idx_transaction_user_cat'),
        ),
    ]
